* code to create tables for multivariate sccs analysis ;

libname OSIM "/data1/SAS_CDM/OSIM";
libname UV "/omop1/dev/ssimpson/OSIM_SCCS_univar";
libname MV "/omop1/dev/ssimpson/OSIM_SCCS_multivar";
libname SM_GE "/omop1/dev/ssimpson/SMALL_GE";
libname SM_OSIM "/omop1/dev/ssimpson/SMALL_OSIM";


proc sql;
	CREATE TABLE sm_osim.SCCS_DATE_OF_CHANGE AS
	SELECT PERSON_ID, observation_period_start_date AS CHANGE_DATE
	FROM sm_osim.OBSERVATION_PERIOD
	UNION
		SELECT PERSON_ID, observation_period_end_date AS CHANGE_DATE
	FROM sm_osim.OBSERVATION_PERIOD
	UNION
	SELECT PERSON_ID, DRUG_ERA_START_DATE AS CHANGE_DATE
	FROM sm_osim.DRUG_ERA7
	UNION
	SELECT PERSON_ID, DRUG_ERA_END_DATE AS CHANGE_DATE
	FROM sm_osim.DRUG_ERA7;
quit;
run;


proc sql;
	CREATE TABLE sm_osim.SCCS_DATE_OF_CHANGE_SORTED AS
	SELECT PERSON_ID, CHANGE_DATE
	FROM sm_osim.SCCS_DATE_OF_CHANGE
	GROUP BY PERSON_ID, CHANGE_DATE
	ORDER BY PERSON_ID, CHANGE_DATE ASC;
quit;
run;


data sm_osim.SCCS_PERIODS_ALL (keep=PERSON_ID PERIOD_START_DATE PERIOD_END_DATE);
	set sm_osim.SCCS_DATE_OF_CHANGE_SORTED;
	by PERSON_ID;
	
	retain this_start this_end CHANGE_DATE;
	
	if first.PERSON_ID then do;
		this_start = CHANGE_DATE;
	end;
	
	else do;
		this_end = CHANGE_DATE;
		PERIOD_START_DATE = this_start;
		PERIOD_END_DATE = this_end;
		this_start = this_end;
		output;
	end;
run;


proc sql;
	CREATE TABLE sm_osim.SCCS_PERIODS AS
	SELECT A.PERSON_ID,
		CASE 
			WHEN (A.PERIOD_START_DATE < O.observation_period_start_date) 
				THEN O.observation_period_start_date
			ELSE A.PERIOD_START_DATE
		END AS PERIOD_START_DATE,
		CASE
			WHEN (A.PERIOD_END_DATE > O.observation_period_end_date)
				THEN O.observation_period_end_date
			ELSE A.PERIOD_END_DATE
		END AS PERIOD_END_DATE 
	FROM sm_osim.SCCS_PERIODS_ALL A
		INNER JOIN sm_osim.OBSERVATION_PERIOD O
		ON A.PERSON_ID = O.PERSON_ID
	WHERE A.PERIOD_START_DATE < O.observation_period_end_date
		AND A.PERIOD_END_DATE > O.observation_period_start_date
		AND rx_data_availability IS NOT NULL
	ORDER BY PERSON_ID, PERIOD_START_DATE ASC;
quit;
run;



proc sql;
	CREATE TABLE sm_osim.SCCS_DRUGS_PER_PERIOD AS
	SELECT DISTINCT P.PERSON_ID,
		P.PERIOD_START_DATE,
		P.PERIOD_END_DATE,
		/*CASE 
			WHEN (D.DRUG_ERA_START_DATE <= P.PERIOD_END_DATE
						AND D.DRUG_ERA_END_DATE > P.PERIOD_START_DATE) 
			THEN */D.DRUG_CONCEPT_ID
			/*ELSE 0
		END AS DRUG_CONCEPT_ID*/

	FROM sm_osim.SCCS_PERIODS P
		INNER JOIN
		sm_osim.DRUG_ERA7 D
		ON P.PERSON_ID = D.PERSON_ID
		WHERE D.DRUG_ERA_START_DATE <= P.PERIOD_END_DATE
			AND D.DRUG_ERA_END_DATE > P.PERIOD_START_DATE;
	ORDER BY PERSON_ID, PERIOD_START_DATE ASC, DRUG_CONCEPT_ID ASC;
quit;
run;	


proc sql;
	CREATE TABLE sm_osim.SCCS_DRUGS_PER_PERIOD2 AS
	SELECT DISTINCT P.PERSON_ID,
		P.PERIOD_START_DATE,
		P.PERIOD_END_DATE,
		CASE 
			WHEN (R.DRUG_CONCEPT_ID IS NULL) THEN 0
			ELSE R.DRUG_CONCEPT_ID
		END AS DRUG_CONCEPT_ID
	FROM sm_osim.SCCS_PERIODS P
		LEFT JOIN sm_osim.SCCS_DRUGS_PER_PERIOD R
		ON P.PERSON_ID = R.PERSON_ID
			AND P.PERIOD_START_DATE = R.PERIOD_START_DATE
			AND P.PERIOD_END_DATE = R.PERIOD_END_DATE
	ORDER BY PERSON_ID, PERIOD_START_DATE ASC, DRUG_CONCEPT_ID ASC;
quit;
run;




proc sql;
	CREATE TABLE sm_osim.SCCS_CASES_PER_PERIOD AS
	SELECT P.PERSON_ID,
		P.PERIOD_START_DATE,
		P.PERIOD_END_DATE,
		P.PERIOD_END_DATE - P.PERIOD_START_DATE AS PERIOD_LENGTH,
		C.CONDITION_CONCEPT_ID,
		COUNT(C.CONDITION_ERA_ID) AS PERIOD_CASE_COUNT
	FROM sm_osim.SCCS_PERIODS P
		LEFT JOIN
		sm_osim.CONDITION_ERA65 C
		ON P.PERSON_ID = C.PERSON_ID
	WHERE C.CONDITION_ERA_START_DATE > P.PERIOD_START_DATE
		AND C.CONDITION_ERA_END_DATE <= P.PERIOD_END_DATE	
	GROUP BY P.PERSON_ID,
		P.PERIOD_START_DATE,
		P.PERIOD_END_DATE,
		C.CONDITION_CONCEPT_ID;
quit;
run;







